spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USER}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none