name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      env:
        DOCKER_LOGIN: ${{secrets.DOCKER_HUB_LOGIN}}
        DOCKER_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
      run: docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN

    - name: Build image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_HUB_LOGIN}}/todo-server:latest

    - name: Push to registry
      run: docker push ${{secrets.DOCKER_HUB_LOGIN}}/todo-server
