name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  test:
    runs-on: ubuntu-latest
   
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-java@v4
       with:
          java-version: '17'
          distribution: 'temurin'
          
     - name: Setup Gradle
       uses: gradle/gradle-build-action@v2

     - name: Make gradlew executable
       run: chmod +x ./gradlew
       
     - name: Run build with Gradle Wrapper
       run: ./gradlew build -x test
       
     - name: Run tests
       run: ./gradlew test
 
  build:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      env:
        DOCKER_LOGIN: ${{secrets.DOCKER_HUB_LOGIN}}
        DOCKER_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
      run: docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN

    - name: Build image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_HUB_LOGIN}}/todo-server:latest

    - name: Push to registry
      run: docker push ${{secrets.DOCKER_HUB_LOGIN}}/todo-server
  
  deploy:
   runs-on: ubuntu-latest
   needs: [build] 

   steps:
     - name: Deploy Image to Render
       run: curl ${{secrets.DEPLOY_HOOK}}
